### ISSUE TITLE
Improve structure of sample app

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#20]
The current structure of the sample app fails to show how route/template nesting works well. Instead of the `albums` route/template not actually doing/rendering anything we should follow the classic side-by-side approach that much better illustrates that key concept of Ember.js:

![ohne titel 2](https://cloud.githubusercontent.com/assets/1510/16647051/96fc6bde-442d-11e6-93ec-c75f24be3dc3.png)

**Comment by 0x8890** [comment]
I guess this has been done :)

https://github.com/simplabs/ember-workshop/pull/21
