### ISSUE TITLE
Fix online workshop teasers

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#24]
We should include the fact that the online workshops are indeed online in the teasers at the top of the page - same style that we teaser the location for the on-location workshops.

**Comment by ganeshbsub** [comment]
Maybe we should remove the time from the online workshop teasers to make them look more consistent with the on-site workshop teaser. Just _"Oct 6.th 2016 \n Online"_ Else they have an extra line and it somehow looks weird.
