### ISSUE TITLE
Get qoutes with right to name quotee

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#35]
We should add names to the quotes on the website. I'll send you a list of people to reach out to and ask for quotes via slack. These new quotes would replace the ones currently on the website. Names should include company names, e.g. `Marco Otte-Witte, simplabs`.

Please assign to @0x8890 and @LevelbossMike for review and merge when you reach consensus while I'm on vacation.

**Comment by ganeshbsub** [comment]
I just got one response to the emails I sent out :'( - 

> I really enjoyed the workshop. It was well-structured and well-delivered, with lots of opportunities to ask questions. At the end, I had a clear understanding of Ember and how to build an Ember app using current best practices. Well done and many thanks for a very useful three days! - Philip Long

**Comment by marcoow** [comment]
can you send follow-ups to the other people?

**Comment by ganeshbsub** [comment]
Another response - 

> I found the workshop a great intro to Ember - as primarily a backender, I am usually more concerned with building APIs for our Ember guys, but the workshop helped orient me to their work. I can now confidently jump in and work on any part of their Ember application when needed. - Mike Timofiiv
