### ISSUE TITLE
Update example apps

### ISSUE THREAD

**Issue by patsy-issa** [simplabs/ember-workshop#360]
- [x] auth 
- [x] routing #362 
- [x] ember-data #365 
- [x] components @marcoow 
- [x] component-composition #378 
- [x] tomster-player @marcoow 
- [x] core-concepts @marcoow 
- [x] dependencies #371 
- [x] services #370 
- [x] web-sockets #380 
- [x] example-addon #382 
- [x] templates

**Comment by marcoow** [comment]
@patsy-issa let's go in order of priority:

* routing
* ember-data
* components
* tomster-player
* component-composition
* dependencies
* services
* web-sockets

**Comment by patsy-issa** [comment]
Picking up routing

**Comment by patsy-issa** [comment]
Picking up ember-data
