### ISSUE TITLE
Broadcasting via socket is broken

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#368]
Broadcasting via sockets is not working properly in the tomster-player app. The broadcasting as such works but the message is also sent to the originator of the event so that the comment appears twice in that instance of the app (one is created explicitly via the store and one is being pushed via the socket). When fixing that it would likely also be good to update socket.io both on the client and in the server.

**Comment by patsy-issa** [comment]
This was resolved in #395  with the addition of socket id, the issue I was investigating here was how did we end up with 2 comment records with the same ID inside the store, the fix introduced in the pr prevents the scenario from happening in the first place.

**Comment by marcoow** [comment]
The reason for the 2 records was one was added via `createRecord`/`save`, the other via `pushPayload` when the socket message came in. Classic broadcasting where the socket message is delivered to all connections **except** the original sender doesn't work here since there is no sender as the action (creation of the record) isn't triggered via a socket message but an HTTP request.
