### ISSUE TITLE
Add header bar

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#37]
similar to footer with our logo and "brought to you by simplabs"

**Comment by marcoow** [comment]
done

**Comment by ganeshbsub** [comment]
@marcoow Isn't this supposed to be auto-closed when referenced in a merge?

**Comment by marcoow** [comment]
@ganeshbsub: only if you put "Closes #x" in the pr description

**Comment by ganeshbsub** [comment]
@marcoow But I have! #40 This is weird.

**Comment by marcoow** [comment]
hm, strange
