### ISSUE TITLE
Make sure content is up to date

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-workshop#49]
reference content: https://mike.works/course/ember-pro-16c648c

**Comment by ganeshbsub** [comment]
@marcoow The timing/duration is different in our site. But that's intentional I guess?

**Comment by ganeshbsub** [comment]
Everything else is fine.

**Comment by ganeshbsub** [comment]
@marcoow Merged and still not closed. Okay, now I have no idea what this works for anymore. I guess it only works if mentioned in a commit?

**Comment by marcoow** [comment]
no, should work when you add `closes #<xyz>` to the PR description

**Comment by ganeshbsub** [comment]
Apparently not, because the PR description does have it. O_o
